### ISSUE TITLE
Installation via Chocolatey doesn't install NoteBar

### ISSUE THREAD

**Issue by Shkvarka** [PavelStefanov/Notebar#1]
Chocolatey is fresh installed, PC rebooted.
"choco install notebar" executed, NoteBar v1.0 installed without errors, PC rebooted.
in TaskBar pop-up menu -> ToolBars (sub-menu) -> no NoteBar option
notebar isn't available in PowerShell (it stays only in Chocolatey/lib/tools/src.zip)

**Comment by PavelStefanov** [comment]
@Shkvarka thank you! Seems like I can reproduce it.

**Comment by PavelStefanov** [comment]
@Shkvarka I hope I've fixed this issue and I've send it to choco. Validation of new package will take some time =(

**Comment by Shkvarka** [comment]
thank you!! Going to check it soon!
